apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: cloudwatch-alerts
type: Opaque
stringData:
  DB_USER: alerts_user
  DB_PASSWORD: alerts_password
  DB_NAME: alerts_db
  AWS_ACCOUNT_ID: "054037143289"
  AWS_REGION: "ap-south-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-pull-secret
  namespace: cloudwatch-alerts
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
